"""Turns a .seam file into TypedDicts a type checker can read.

The generated module holds no validation rules. If you delete it everything
still runs; you only lose static checking. That is the test that it is not a
second source of truth.

The mapping that matters is presence, because `NotRequired` exists in Python's
type system for exactly the distinction Seam makes:

    String            ->  x: str
    String?           ->  x: str | None
    optional String   ->  x: NotRequired[str]
    optional String?  ->  x: NotRequired[str | None]
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ._seam import Schema

HEADER = '''\
# Generated by `seam typegen` from {source}. Do not edit.
#
# This file carries shape, not rules. Validation happens in the engine against
# the .seam file at runtime; deleting this only costs you static checking.
from __future__ import annotations

import datetime
import sys
from pathlib import Path
from typing import Literal, TypedDict, cast

if sys.version_info >= (3, 11):
    from typing import NotRequired
else:
    from typing_extensions import NotRequired

from seam import Schema

_SCHEMA = Schema.load(Path(__file__).parent / "{schema_file}")
'''

VALIDATOR = '''

def validate_{snake}(payload: object) -> {name}:
    """Validate against `{name}` in {schema_file}."""
    return cast({name}, _SCHEMA.validate("{name}", payload))
'''


def _snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def _annotate(ty: dict[str, Any]) -> str:
    kind = ty["kind"]
    if kind == "bool":
        return "bool"
    if kind == "int":
        return "int"
    if kind == "float":
        return "float"
    if kind == "string":
        return "str"
    if kind == "date":
        return "datetime.date"
    if kind == "datetime":
        return "datetime.datetime"
    if kind == "enum":
        values = ", ".join(f'"{v}"' for v in ty["values"])
        return f"Literal[{values}]"
    if kind == "array":
        item = _annotate(ty["item"])
        if ty["item_nullable"]:
            item = f"{item} | None"
        return f"list[{item}]"
    # A reference needs no quoting: the header imports postponed annotations,
    # so a type may refer to one defined later in the file, the same way the
    # .seam parser resolves references in a second pass.
    if kind == "ref":
        return ty["name"]
    if kind == "object":
        return ty["object"]["name"]
    raise ValueError(f"unknown type kind: {kind!r}")


def _field_annotation(field: dict[str, Any]) -> str:
    annotation = _annotate(field["type"])
    if field["nullable"]:
        annotation = f"{annotation} | None"
    if field["optional"]:
        annotation = f"NotRequired[{annotation}]"
    return annotation


def _typed_dict(described: dict[str, Any]) -> str:
    name = described["name"]
    lines = [f"class {name}(TypedDict):"]
    if not described["fields"]:
        lines.append("    pass")
    for field in described["fields"]:
        lines.append(f'    {field["name"]}: {_field_annotation(field)}')
    return "\n".join(lines)


def generate(schema_path: Path | str) -> str:
    """Render the module source for one .seam file."""
    schema_path = Path(schema_path)
    schema = Schema.load(schema_path)
    described = schema.describe()

    parts = [
        HEADER.format(source=schema_path.name, schema_file=schema_path.name),
    ]
    for name in sorted(described):
        parts.append("\n\n" + _typed_dict(described[name]) + "\n")
    for name in sorted(described):
        parts.append(
            VALIDATOR.format(
                snake=_snake(name), name=name, schema_file=schema_path.name
            )
        )
    return "".join(parts)


def output_path(schema_path: Path | str) -> Path:
    """Where `generate` output belongs by default: alongside the .seam file."""
    schema_path = Path(schema_path)
    return schema_path.with_name(f"{schema_path.stem}_types.py")
