"""Turns a .seam file into TypedDicts a type checker can read.

The generated module holds no validation rules. If you delete it everything
still runs; you only lose static checking. That is the test that it is not a
second source of truth.

The mapping that matters is presence, because `NotRequired` exists in Python's
type system for exactly the distinction Seam makes:

    String            ->  x: str
    String?           ->  x: str | None
    optional String   ->  x: NotRequired[str]
    optional String?  ->  x: NotRequired[str | None]
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ._seam import Schema

HEADER = '''\
# Generated by `seam typegen` from {source}. Do not edit.
#
# This file carries shape, not rules. Validation happens in the engine against
# the .seam file at runtime; deleting this only costs you static checking.
from __future__ import annotations

import datetime
import sys
from pathlib import Path
from typing import Literal, TypedDict, Union, cast

if sys.version_info >= (3, 11):
    from typing import NotRequired
else:
    from typing_extensions import NotRequired

from seam import Schema

_SCHEMA = Schema.load(Path(__file__).parent / "{schema_file}")
'''

VALIDATOR = '''
# Bound once at import: the type lookup and the datetime classes are resolved
# here rather than on every call.
_{upper} = _SCHEMA.validator("{name}")


def validate_{snake}(payload: object) -> {name}:
    """Validate against `{name}` in {schema_file}.

    Takes a dict, or raw JSON as `bytes` or `str`. Hand it the bytes when you
    have them: Seam parses them itself, which is what keeps a 64-bit integer
    intact on every runtime.
    """
    return cast({name}, _{upper}(payload))

'''

def _snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def _annotate(ty: dict[str, Any]) -> str:
    kind = ty["kind"]
    if kind == "bool":
        return "bool"
    if kind == "int":
        return "int"
    if kind == "float":
        return "float"
    if kind == "string":
        return "str"
    if kind == "date":
        return "datetime.date"
    if kind == "datetime":
        return "datetime.datetime"
    if kind == "enum":
        values = ", ".join(f'"{v}"' for v in ty["values"])
        return f"Literal[{values}]"
    if kind == "array":
        item = _annotate(ty["item"])
        if ty["item_nullable"]:
            item = f"{item} | None"
        return f"list[{item}]"
    # A reference needs no quoting: the header imports postponed annotations,
    # so a type may refer to one defined later in the file, the same way the
    # .seam parser resolves references in a second pass.
    if kind == "ref":
        return ty["name"]
    if kind == "object":
        return ty["object"]["name"]
    raise ValueError(f"unknown type kind: {kind!r}")

def _field_annotation(field: dict[str, Any]) -> str:
    annotation = _annotate(field["type"])
    if field["nullable"]:
        annotation = f"{annotation} | None"
    if field["optional"]:
        annotation = f"NotRequired[{annotation}]"
    return annotation

def _typed_dict(described: dict[str, Any]) -> str:
    name = described["name"]
    lines = [f"class {name}(TypedDict):"]
    if not described["fields"]:
        lines.append("    pass")
    for field in described["fields"]:
        lines.append(f'    {field["name"]}: {_field_annotation(field)}')
    return "\n".join(lines)

def _variant_name(union: str, variant: str, taken: set[str]) -> str:
    """A name for the variant-with-its-tag, stepped aside if it is taken."""
    candidate = f"{union}{variant}"
    while candidate in taken:
        candidate += "_"
    return candidate

def _union(described: dict[str, Any], taken: set[str]) -> str:
    """A tagged union, as a `Union` of TypedDicts that each pin the tag.

    The tag is added here rather than read off the variant, because in the
    `.seam` file it belongs to the union: no variant may declare it. Pinning it
    to a `Literal` is what lets a type checker narrow on it, which is the same
    thing the TypeScript generator gets from a discriminated union.
    """
    tag = described["tag"]
    name = described["name"]
    blocks: list[str] = []
    arms: list[str] = []

    for variant in described["variants"]:
        arm = _variant_name(name, variant["type"], taken)
        taken.add(arm)
        arms.append(arm)
        blocks.append(
            f'class {arm}({variant["type"]}):\n'
            f'    {tag}: Literal["{variant["tag"]}"]\n'
        )

    blocks.append(f'{name} = Union[{", ".join(arms)}]\n')
    return "\n\n".join(blocks)

def generate(schema_path: Path | str) -> str:
    """Render the module source for one .seam file."""
    schema_path = Path(schema_path)
    schema = Schema.load(schema_path)
    described = schema.describe()

    names = sorted(described)
    taken = set(names)
    objects = [n for n in names if described[n].get("kind") != "union"]
    unions = [n for n in names if described[n].get("kind") == "union"]

    parts = [
        HEADER.format(source=schema_path.name, schema_file=schema_path.name),
    ]
    # Objects first. A union's arms subclass them, and a class statement runs
    # at import, unlike an annotation, which the header defers.
    for name in objects:
        parts.append("\n\n" + _typed_dict(described[name]) + "\n")
    for name in unions:
        parts.append("\n\n" + _union(described[name], taken))
    for name in names:
        parts.append(
            VALIDATOR.format(
                snake=_snake(name),
                upper=_snake(name).upper(),
                name=name,
                schema_file=schema_path.name,
            )
        )
    return "".join(parts)


def output_path(schema_path: Path | str) -> Path:
    """Where `generate` output belongs by default: alongside the .seam file."""
    schema_path = Path(schema_path)
    return schema_path.with_name(f"{schema_path.stem}_types.py")
