'use strict'

/**
 * Turns a .seam file into TypeScript a compiler can read.
 *
 * The generated file holds no validation rules — and, unlike the Python one,
 * no code at all. It is types only. That is the strongest form of the test
 * that it is not a second source of truth: delete it and nothing stops
 * running, because there was nothing running in it.
 *
 * The mapping that matters is presence, because TypeScript already has the
 * vocabulary. `?:` is the absence axis, exactly as `NotRequired` is in Python:
 *
 *     String            ->  x: string
 *     String?           ->  x: string | null
 *     optional String   ->  x?: string
 *     optional String?  ->  x?: string | null
 */

const { basename, extname, dirname, join } = require('node:path')

const { Schema } = require('./index.js')

const HEADER = (source, mapName, firstType) => `\
// Generated by \`seam typegen\` from ${source}. Do not edit.
//
// Shape, not rules. Validation happens in the engine against ${source} at
// runtime; this file is types only, so deleting it costs you static checking
// and nothing else.
//
//     import { Schema } from 'seam-schema'
//     import type { ${mapName} } from './${outputName(source).replace(/\.ts$/, '')}'
//
//     const schema = Schema.load<${mapName}>('${source}')
//     const ${lowerFirst(firstType)} = schema.validator('${firstType}').validate(bytes)
//
// Two mappings are worth knowing before you read the types below:
//
//   - \`u64\` and \`i64\` are \`bigint\`. A \`number\` cannot hold them, and one
//     that looks like it can is already the wrong value.
//   - \`Date\` is \`string\`, not \`Date\`. JavaScript has no date-only type, and
//     pushing a calendar date through an instant is what produces
//     off-by-one-day bugs. \`DateTime\` is a real \`Date\`.`

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function lowerFirst(name) {
  return name.charAt(0).toLowerCase() + name.slice(1)
}

/** A property name, quoted only when it has to be. */
function key(name) {
  return IDENTIFIER.test(name) ? name : JSON.stringify(name)
}

function stringLiteral(value) {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function annotate(ty) {
  switch (ty.kind) {
    case 'bool':
      return 'boolean'
    // The one place the width of an integer reaches the type system: past
    // 2^53 a `number` is not the value that was sent, so the engine hands
    // back a bigint and the type has to say so.
    case 'int':
      return ty.fitsJsNumber ? 'number' : 'bigint'
    case 'float':
      return 'number'
    case 'string':
      return 'string'
    // A calendar date stays the ISO string it arrived as. See the header.
    case 'date':
      return 'string'
    case 'datetime':
      return 'Date'
    case 'enum':                    
      return ty.values.map(stringLiteral).join(' | ')
    case 'array': {
      let item = annotate(ty.item)
      if (ty.itemNullable) item = `${item} | null`
      // An element has two states, a value or null; absence is a property of
      // a key and an array has no keys, so `?` never appears here.
      return item.includes('|') ? `(${item})[]` : `${item}[]`
    }
    // A reference needs no forward declaration: TypeScript resolves the whole
    // file before checking it, the way the .seam parser resolves references in
    // a second pass.
    case 'ref':
      return ty.name
    case 'object':
      return ty.object.name
    default:
      throw new Error(`unknown type kind: ${JSON.stringify(ty.kind)}`)
  }
}

function property(field) {
  let annotation = annotate(field.type)
  if (field.nullable) annotation = `${annotation} | null`
  // `?:` is absence. It is a different key from `| null`, which is the value
  // being null, and TypeScript is one of the few languages that says so.
  const optional = field.optional ? '?' : ''
  return `  ${key(field.name)}${optional}: ${annotation}`
}

function iface(described) {
  const lines = [`export interface ${described.name} {`]
  for (const field of described.fields) lines.push(property(field))
  lines.push('}')
  return lines.join('\n')
}

/**
 * A tagged union, as TypeScript's own discriminated union.
 *
 * The tag is intersected in rather than written on the variant, because in the
 * .seam file it belongs to the union: no variant may declare it. What
 * TypeScript gets in return is narrowing — `if (e.type === 'created')` makes
 * the rest of `e` the created variant, checked by the compiler.
 */
function union(described) {
  const arms = described.variants.map(
    (v) => `  | (${v.type} & { ${key(described.tag)}: ${stringLiteral(v.tag)} })`,
  )
  return [`export type ${described.name} =`, ...arms].join('\n')
}

function declaration(described) {
  return described.kind === 'union' ? union(described) : iface(described)
}

/**
 * The name of the map interface: derived from the file, and stepped aside if
 * the schema happens to declare a type by that name.
 */
function mapName(source, declared) {
  const stem = basename(source, extname(source))
  const pascal = stem
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
  const base = IDENTIFIER.test(pascal) ? pascal : 'Seam'
  for (const candidate of [`${base}Types`, `${base}SchemaTypes`, `Seam${base}Types`]) {
    if (!declared.includes(candidate)) return candidate
  }
  return `Seam${base}Types_`
}

function typeMap(name, source, declared) {
  const lines = [
    '/**',
    ` * Every type in ${source}, keyed by the name the schema gives it.`,
    ' *',
    ' * Hand this to `Schema.load` and every validator it produces is typed,',
    ' * and a misspelled type name becomes a compile error rather than a',
    ' * runtime one.',
    ' */',
    `export interface ${name} {`,
  ]
  for (const type of declared) lines.push(`  ${key(type)}: ${type}`)
  lines.push('}')
  return lines.join('\n')
}

/** Renders the TypeScript source for one .seam file. */
function generate(schemaPath) {
  const described = Schema.load(schemaPath).describe()
  const source = basename(schemaPath)
  const declared = Object.keys(described).sort()
  const map = mapName(source, declared)

  const parts = [HEADER(source, map, declared[0] ?? 'Type')]
  for (const name of declared) parts.push(declaration(described[name]))
  parts.push(typeMap(map, source, declared))
  return parts.join('\n\n') + '\n'
}

function outputName(schemaFile) {
  return `${basename(schemaFile, extname(schemaFile))}.types.ts`
}

/** Where `generate` output belongs by default: alongside the .seam file. */
function outputPath(schemaPath) {
  return join(dirname(schemaPath), outputName(schemaPath))
}

module.exports = { generate, outputPath, outputName }
